"""initial schema

Revision ID: e3e71370f97f
Revises: 
Create Date: 2026-07-27 16:27:44.643908
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3e71370f97f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=32), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('checksum_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_files_sha256'), ['sha256'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('model_registry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('preprocessing', sa.String(length=16), nullable=True),
    sa.Column('max_len', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'version', name='uq_model_kind_version')
    )
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_kind'), ['kind'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mrn', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=True)

    op.create_table('visits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('visit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('gestational_age_weeks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_patient_id'), ['patient_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('visit_id', sa.String(length=32), nullable=True),
    sa.Column('audio_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('asr_model', sa.String(length=64), nullable=True),
    sa.Column('classifier_version', sa.String(length=64), nullable=True),
    sa.Column('ner_version', sa.String(length=64), nullable=True),
    sa.Column('rules_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_audio_id'), ['audio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('report_items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_rephrased', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('label_ar', sa.String(length=128), nullable=True),
    sa.Column('soap_section', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_calibrated', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=16), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('timestamp_precision', sa.String(length=16), nullable=False),
    sa.Column('source_segment_index', sa.Integer(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('review_priority', sa.Float(), nullable=True),
    sa.Column('entity_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_report_items_job_order', ['job_id', 'order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_items_label'), ['label'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio', sa.JSON(), nullable=False),
    sa.Column('pipeline_meta', sa.JSON(), nullable=False),
    sa.Column('patient_info', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_job_id'), ['job_id'], unique=True)

    op.create_table('suggestions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('rule_version', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('title_ar', sa.Text(), nullable=False),
    sa.Column('detail_ar', sa.Text(), nullable=False),
    sa.Column('missing_tests', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('inference_chain', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_severity'), ['severity'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('no_speech_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_job_id'), ['job_id'], unique=True)

    op.create_table('corrections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['report_items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_item_id'), ['item_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('assertion', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value2', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('extractor', sa.String(length=32), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['report_items.item_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_patient_id'), ['patient_id'], unique=False)

    op.create_table('suggestion_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('suggestion_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_feedback_suggestion_id'), ['suggestion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_feedback_suggestion_id'))

    op.drop_table('suggestion_feedback')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_patient_id'))
        batch_op.drop_index(batch_op.f('ix_entities_job_id'))
        batch_op.drop_index(batch_op.f('ix_entities_item_id'))
        batch_op.drop_index(batch_op.f('ix_entities_code'))

    op.drop_table('entities')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_item_id'))

    op.drop_table('corrections')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_job_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_severity'))
        batch_op.drop_index(batch_op.f('ix_suggestions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_job_id'))

    op.drop_table('suggestions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_job_id'))

    op.drop_table('reports')
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_items_label'))
        batch_op.drop_index('ix_report_items_job_order')
        batch_op.drop_index(batch_op.f('ix_report_items_job_id'))

    op.drop_table('report_items')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_audio_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_patient_id'))

    op.drop_table('visits')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))

    op.drop_table('patients')
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_registry_kind'))

    op.drop_table('model_registry')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_files_sha256'))

    op.drop_table('audio_files')
    # ### end Alembic commands ###
