"""asr quality and speaker fields

Revision ID: 5059d7197646
Revises: 5510797204e4
Create Date: 2026-07-27 18:21:10.230437
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5059d7197646'
down_revision: Union[str, None] = '5510797204e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combined_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('speaker_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_asr_suspect', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.drop_column('is_asr_suspect')
        batch_op.drop_column('speaker_confidence')
        batch_op.drop_column('combined_confidence')

    # ### end Alembic commands ###
