"""patient states

Revision ID: 5510797204e4
Revises: e3e71370f97f
Create Date: 2026-07-27 16:51:05.403360
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5510797204e4'
down_revision: Union[str, None] = 'e3e71370f97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_states',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ga_weeks', sa.Integer(), nullable=True),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('edd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_states_effective_at'), ['effective_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_states_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_patient_states_patient_time', ['patient_id', 'effective_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_states_patient_time')
        batch_op.drop_index(batch_op.f('ix_patient_states_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_states_effective_at'))

    op.drop_table('patient_states')
    # ### end Alembic commands ###
