"""uncertainty and multilabel fields

Revision ID: 8f8ec9d933cd
Revises: 5059d7197646
Create Date: 2026-07-27 22:05:37.387111
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f8ec9d933cd'
down_revision: Union[str, None] = '5059d7197646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labels', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('also_in_sections', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('entropy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ood_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low_confidence_reasons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.drop_column('low_confidence_reasons')
        batch_op.drop_column('ood_score')
        batch_op.drop_column('entropy')
        batch_op.drop_column('also_in_sections')
        batch_op.drop_column('labels')

    # ### end Alembic commands ###
